name: Update PJ Branches

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

  workflow_dispatch:

jobs:
  list_pj_branches:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v3
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: List PJ branches
        id: pj_list
        run: |
          git remote set-branches origin '*'
          git fetch
          pj_list=$(git branch -r --list '*/pj-*' --format='%(refname:short)' | sed 's/origin\///g' | tr '\n' ' ' | awk '{gsub(/[^ ]+/,"\x22&\x22\x2C");print}' | sed 's/\x2C $//')
          echo $pj_list
          pj_list_json=$(echo '\'['${pj_list}'\'']' | jq -c)
          echo $pj_list_json
          echo "::set-output name=branches::${pj_list_json}"
      
  update_pj_branches:
    needs: list_pj_branches
    strategy:
      matrix:
        branch: ${{fromJson(needs.list_pj_branches.outputs.branches)}}
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Create develop_to_pj branch 
        run: |
          git branch develop_to_${branch} origin/${branch}
          git push origin develop_to_${branch}
      
      - name: Try to merge develop
        run: |
          git checkout develop_to_${branch}
          if git merge --no-ff --no-commit origin/develop; then
            echo "develop can be merged into develop_to_${branch}"
            git commit -m "Merge develop into develop_to_${branch}"
            git push origin develop_to_${branch}
            gh pr create -B ${branch} --head develop_to_${branch} -t "Update ${branch} from develop" -b ""
          else
            echo "develop can not be merged into develop_to_${branch}"
            git merge --abort
            payload='{
              "attachments": [{
                "title": "Conflict detected merging develop into develop_to_'${branch}' on run ID '${GITHUB_RUN_ID}'",
                "title_link": "'${GITHUB_SERVER_URL}'/'${GITHUB_REPOSITORY}'/actions/runs/'${GITHUB_RUN_ID}'",
                "color": "danger"
              }]
            }'
            body=$(echo $payload | jq -c)
            curl -X POST -H "Content-Type: application/json" -d "$body" ${{ secrets.SLACK_WEBHOOK}}
          fi
