name: Update PJ Branches

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      
      - name: List PJ branches
        id: pj_list
        run: |
          git remote set-branches origin '*'
          git fetch
          pj_list=$(git branch -a --list 'pj-*')
          echo "$(pj_list)"
          echo "$(git branch -a)"
          echo "::set-output name=branches::$pj_list"

      - run: echo "${{ steps.pj_list.branches}}"
